blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/yourusername/yourrepo/discussions
    about: For questions and discussions

template_chooser:
  enabled: true
  paths:
    - .github/PULL_REQUEST_TEMPLATE/feature.md
    - .github/PULL_REQUEST_TEMPLATE/develop-main.md
    - .github/PULL_REQUEST_TEMPLATE/hotfix.md
