name: Release

on:
    push:
        tags:
            - "v*-ds"
    release:
        types: [created]
    workflow_dispatch:

jobs:
    github-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v3
              with:
                  version: 9.4.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Build packages
              run: pnpm run build

            - name: Get upstream version
              id: upstream_version
              run: |
                  UPSTREAM_VERSION=$(node -p "require('./package.json').upstreamVersion")
                  echo "UPSTREAM_VERSION=${UPSTREAM_VERSION}" >> $GITHUB_ENV

            - name: Create Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  generate_release_notes: true
                  body: |
                      This release is based on upstream version: ${{ env.UPSTREAM_VERSION }}

                      ## Compatibility
                      This version includes DarkSun custom features on top of Eliza ${{ env.UPSTREAM_VERSION }}.

                      ## Installation
                      ```bash
                      git clone https://github.com/darksunexists/ds-eliza.git
                      cd ds-eliza
                      git checkout ${{ github.ref_name }}
                      pnpm install
                      ```

    npm-publish:
        runs-on: ubuntu-latest
        needs: github-release
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v3
              with:
                  version: 9.4.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23"
                  cache: "pnpm"

            - name: Configure Git
              run: |
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor }}@users.noreply.github.com"

            - name: Setup npm registry
              run: |
                  npm config set registry https://registry.npmjs.org/
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Install Protobuf Compiler
              run: sudo apt-get install -y protobuf-compiler

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Build packages
              run: pnpm run build

            - name: Publish to npm
              run: |
                  # Get the latest release tag
                  LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

                  # Force clean the working directory and reset any changes
                  echo "Cleaning working directory and resetting any changes"
                  git clean -fd
                  git reset --hard HEAD

                  # Force checkout the latest tag
                  echo "Checking out latest tag: $LATEST_TAG"
                  git checkout -b temp-publish-branch $LATEST_TAG

                  echo "Publishing version: $LATEST_TAG"
                  npx lerna publish from-package --yes --dist-tag latest
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
