name: PR Review Requirements

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches: [main]

jobs:
  pr-workflow:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure git credentials
        run: |
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Check branch naming convention
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          BASE_BRANCH=${GITHUB_BASE_REF}

          if [[ $BASE_BRANCH == "develop" && ! $BRANCH_NAME =~ ^feature/ ]]; then
            echo "PRs to develop must use feature/* branch naming"
            exit 1
          fi

          if [[ $BASE_BRANCH == "main" && ! $BRANCH_NAME =~ ^(hotfix/|develop$) ]]; then
            echo "PRs to main must be from develop or hotfix/* branches"
            exit 1
          fi

      - name: Set PR requirements
        if: startsWith(github.head_ref, 'hotfix/')
        run: |
          echo "::warning::🚨 HOTFIX PR DETECTED - Expedited review required"
